[package]
name = "my-vec"
version = "0.1.0"
authors = ["João M. Bezerra <marcospb19@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
